package com.venera.compose.feature

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import top.yukonga.miuix.kmp.theme.Colors

/** Semantic bridge verified against Miuix 0.9.4-rc01 Colors.copy, not Material token names. */
internal fun ColorScheme.toMiuixColors(base: Colors): Colors = base.copy(
    primary = primary,
    onPrimary = onPrimary,
    primaryVariant = primaryContainer,
    onPrimaryVariant = onPrimaryContainer,
    error = error,
    onError = onError,
    errorContainer = errorContainer,
    onErrorContainer = onErrorContainer,
    disabledPrimary = onSurface.copy(alpha = 0.12f),
    disabledOnPrimary = onSurface.copy(alpha = 0.38f),
    disabledPrimaryButton = onSurface.copy(alpha = 0.12f),
    disabledOnPrimaryButton = onSurface.copy(alpha = 0.38f),
    disabledPrimarySlider = primary.copy(alpha = 0.38f),
    primaryContainer = primaryContainer,
    onPrimaryContainer = onPrimaryContainer,
    secondary = secondary,
    onSecondary = onSecondary,
    secondaryVariant = secondaryContainer,
    onSecondaryVariant = onSecondaryContainer,
    disabledSecondary = onSurface.copy(alpha = 0.12f),
    disabledOnSecondary = onSurface.copy(alpha = 0.38f),
    disabledSecondaryVariant = onSurface.copy(alpha = 0.12f),
    disabledOnSecondaryVariant = onSurface.copy(alpha = 0.38f),
    secondaryContainer = secondaryContainer,
    onSecondaryContainer = onSecondaryContainer,
    secondaryContainerVariant = secondaryContainer,
    onSecondaryContainerVariant = onSecondaryContainer,
    tertiaryContainer = tertiaryContainer,
    onTertiaryContainer = onTertiaryContainer,
    tertiaryContainerVariant = tertiaryContainer,
    background = background,
    onBackground = onBackground,
    onBackgroundVariant = onSurfaceVariant,
    surface = surface,
    onSurface = onSurface,
    surfaceVariant = surfaceContainerLow,
    onSurfaceSecondary = onSurfaceVariant,
    onSurfaceVariantSummary = onSurfaceVariant,
    onSurfaceVariantActions = onSurfaceVariant,
    disabledOnSurface = onSurface.copy(alpha = 0.38f),
    surfaceContainer = surfaceContainer,
    onSurfaceContainer = onSurface,
    onSurfaceContainerVariant = onSurfaceVariant,
    surfaceContainerHigh = surfaceContainerHigh,
    onSurfaceContainerHigh = onSurface,
    surfaceContainerHighest = surfaceContainerHighest,
    onSurfaceContainerHighest = onSurface,
    outline = outline,
    dividerLine = outlineVariant,
    windowDimming = scrim.copy(alpha = 0.32f),
    sliderKeyPoint = onPrimaryContainer,
    sliderKeyPointForeground = onPrimary,
    sliderBackground = secondaryContainer,
)

/** Material components also receive the native Miuix palette while in Miuix mode. */
internal fun Colors.toMaterialColors(isDark: Boolean): ColorScheme {
    val base = if (isDark) darkColorScheme() else lightColorScheme()
    return base.copy(
        primary = primary,
        onPrimary = onPrimary,
        primaryContainer = primaryContainer,
        onPrimaryContainer = onPrimaryContainer,
        inversePrimary = primaryVariant,
        secondary = secondary,
        onSecondary = onSecondary,
        secondaryContainer = secondaryContainer,
        onSecondaryContainer = onSecondaryContainer,
        tertiary = onTertiaryContainer,
        onTertiary = tertiaryContainer,
        tertiaryContainer = tertiaryContainer,
        onTertiaryContainer = onTertiaryContainer,
        background = background,
        onBackground = onBackground,
        surface = surface,
        onSurface = onSurface,
        surfaceVariant = surfaceVariant,
        onSurfaceVariant = onSurfaceVariantSummary,
        surfaceTint = primary,
        inverseSurface = onSurface,
        inverseOnSurface = surface,
        error = error,
        onError = onError,
        errorContainer = errorContainer,
        onErrorContainer = onErrorContainer,
        outline = outline,
        outlineVariant = dividerLine,
        scrim = Color.Black,
        surfaceBright = surfaceVariant,
        surfaceDim = surfaceContainerHigh,
        surfaceContainerLowest = background,
        surfaceContainerLow = surfaceVariant,
        surfaceContainer = surfaceContainer,
        surfaceContainerHigh = surfaceContainerHigh,
        surfaceContainerHighest = surfaceContainerHighest,
    )
}
